company:
    name: "schnee"
server:
    host: "0.0.0.0"
    port: 80
    timezone: "Asia/Taipei"
http:
  header:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Headers: "Content-Type, Authorization"
    Access-Control-Allow-Methods: "GET, POST, OPTIONS, HEAD, PATCH, DELETE"

