test:
    dialect: mysql
    datasource: root:123456@tcp(172.18.0.2)/test?parseTime=true
    dir: ./migrations
    table: migrations
development:
    dialect: mysql
    datasource: root:123456@tcp(172.18.0.2)/webtest?parseTime=true
    dir: ./migrations
    table: migrations
