test:
    dialect: mysql
    datasource: root:123456@tcp(0.0.0.0:3306)/test?parseTime=true
    dir: ./migrations
    table: migrations
development:
    dialect: mysql
    datasource: root:123456@tcp(0.0.0.0:3306)/webtest?parseTime=true
    dir: ./migrations
    table: migrations
